# Basic set up for three package managers
version: 2
updates:
  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # Specify labels for Composer pull requests
    labels:
      - "dependencies"
    groups:
      patch-updates:
        patterns:
          - '*'
        update-types:
          - "patch"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
