coverage:
  if: true
  paths:
    - coverage.xml
codeToTestRatio:
  code:
    - 'app/**/*.php'
  test:
    - 'test/**/*.php'
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
push:
  if: is_default_branch
comment:
  if: is_pull_request
summary:
  if: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
